// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArORJcqaMkdjvSECuxYnMtBZS4DdjL77g',
    appId: '1:412913253090:web:0cee84f6bd28fc128efcbb',
    messagingSenderId: '412913253090',
    projectId: 'schoolmanagement-815bf',
    authDomain: 'schoolmanagement-815bf.firebaseapp.com',
    storageBucket: 'schoolmanagement-815bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtu2nb6QstcKYO0C5Yn4J19ARXdJ7F2P0',
    appId: '1:412913253090:android:a4f5419e797944168efcbb',
    messagingSenderId: '412913253090',
    projectId: 'schoolmanagement-815bf',
    storageBucket: 'schoolmanagement-815bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ulx2xAsbtQn97HBB6Tdb86OBti4cOQU',
    appId: '1:412913253090:ios:6550bb1e952a905b8efcbb',
    messagingSenderId: '412913253090',
    projectId: 'schoolmanagement-815bf',
    storageBucket: 'schoolmanagement-815bf.appspot.com',
    iosBundleId: 'com.example.schoolManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ulx2xAsbtQn97HBB6Tdb86OBti4cOQU',
    appId: '1:412913253090:ios:b744716b1ed1b1d38efcbb',
    messagingSenderId: '412913253090',
    projectId: 'schoolmanagement-815bf',
    storageBucket: 'schoolmanagement-815bf.appspot.com',
    iosBundleId: 'com.example.schoolManagement.RunnerTests',
  );
}
